name: players_info
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_storage: ^12.3.5
  flutter:
    sdk: flutter
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
