name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_html: ^3.0.0-beta.2
  http: ^1.2.2
  intl: ^0.20.1
  smooth_page_indicator: ^1.2.0+3
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/image.png
   - assets/jpg/
